### PR TITLE
Use batch size parameter for test data loader in bioHSIC

### PR DESCRIPTION
**Pull request by h6197627**

### CODE REVIEW

**Comment by darsnack** [comment]
Thanks for the PR! The batch size is directly coupled to the learning rule. But for testing, we probably want to use a much larger batch size to speed up evaluation. Maybe adding a different parameter for testing will be better.

**Comment by h6197627** [comment]
Thank you for sharing your research!
Yes, probably, separate parameter will be better. With 256 test batch size in **train-biohsic.py** I just got out of memory with 11GB GPU. So, I tried to overcome this and at the same time unify code as **train-hsic.py** and  **train-bp.py** scripts use `cfg.data.batchsize` for test dataloader as well.

**Comment by darsnack** [comment]
Makes sense! If you can edit the YAML files such as [these](https://github.com/darsnack/biological-hsic/blob/main/configs/data/mnist.yaml) to have lines like:
```yaml
batchsize: 6
test_batchsize: 256
```
And modify the scripts accordingly, then I'm happy to merge the changes.

**Comment by h6197627** [comment]
@darsnack, sorry for delay. I updated PR with new parameter

**Comment by h6197627** [comment]
@darsnack, kind reminder :)

**Comment by darsnack** [comment]
Thanks!

**Pull request merged**
